-- NutriScan AI Database Schema

-- 1. Profiles table expansion
-- Note: Assuming public.profiles already exists from Supabase Auth or initial setup
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    full_name TEXT,
    avatar_url TEXT,
    email TEXT,
    is_admin BOOLEAN DEFAULT false,
    scans_remaining INTEGER DEFAULT 999999,
    last_scan_reset TIMESTAMPTZ DEFAULT NOW(),
    gender TEXT,
    age INTEGER,
    weight_kg DECIMAL,
    height_cm DECIMAL,
    activity_level TEXT,
    nutritional_goals JSONB DEFAULT '{"calories": 2000, "protein": 50, "carbs": 275, "fat": 78, "sugar": 50, "sodium": 2300}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Daily Logs for nutritional tracking
CREATE TABLE IF NOT EXISTS public.daily_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    food_name TEXT NOT NULL,
    calories DECIMAL DEFAULT 0,
    protein DECIMAL DEFAULT 0,
    carbs DECIMAL DEFAULT 0,
    fat DECIMAL DEFAULT 0,
    sugar DECIMAL DEFAULT 0,
    sodium DECIMAL DEFAULT 0,
    logged_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Scan History
CREATE TABLE IF NOT EXISTS public.scan_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    scan_type TEXT NOT NULL, -- 'label', 'food', 'gym'
    scan_data JSONB NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Health Goals
CREATE TABLE IF NOT EXISTS public.health_goals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    goal_type TEXT NOT NULL,
    target TEXT NOT NULL,
    timeline TEXT,
    notes TEXT,
    progress INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Analytics
CREATE TABLE IF NOT EXISTS public.analytics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    event_type TEXT NOT NULL,
    event_data JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. System Settings
CREATE TABLE IF NOT EXISTS public.system_settings (
    id INTEGER PRIMARY KEY,
    free_scans_per_day INTEGER DEFAULT 999999,
    registration_enabled BOOLEAN DEFAULT true,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insert default settings
INSERT INTO public.system_settings (id, free_scans_per_day, registration_enabled)
VALUES (1, 999999, true)
ON CONFLICT (id) DO NOTHING;

-- Enable Row Level Security (RLS)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.daily_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.scan_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.health_goals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.analytics ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.system_settings ENABLE ROW LEVEL SECURITY;

-- Basic RLS Policies
CREATE POLICY "Users can view their own profile" ON public.profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update their own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);

CREATE POLICY "Users can view their own logs" ON public.daily_logs FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own logs" ON public.daily_logs FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can view their own history" ON public.scan_history FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own history" ON public.scan_history FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can view their own goals" ON public.health_goals FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own goals" ON public.health_goals FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can delete their own goals" ON public.health_goals FOR DELETE USING (auth.uid() = user_id);

CREATE POLICY "Public can view settings" ON public.system_settings FOR SELECT USING (true);
